name: 课程

on:
  schedule:
    - cron: "29 14 * * *"

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: 检出仓库
        uses: actions/checkout@v2

      - name: 设置Node.js环境
        uses: actions/setup-node@v2
        with:
          node-version: "18" # 指定Node.js版本

      - name: 安装依赖
        run: npm install

      - name: 执行脚本
        run: node ./app/index.js
